server:
  port: 9527
spring:
  application:
    name: cloud-gateway     # 整个应用的名字
  cloud:
    gateway:

      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes: # routes : 路由（id + uri + 断言 + 过滤器）   - ：表示是个数组
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址 （代理的路由）
          uri: lb://cloud-payment-service # lb :// 服务代理实例名字
          predicates:
            - Path=/payment/getPaymentById/**   #断言,路径相匹配的进行路由  （根据路径进行匹配）

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            # - After=时间         在这个时间之后允许访问
            # - Before=时间         在这个时间之前允许访问
            # - Between=时间1,时间2 在这两个时间之间允许访问
            # - Cookie=username,zwx 请求携带cookie必须带username属性，值为zwx



eureka:
  instance:
    hostname: cloud-gateway-service   #单个实例的名字
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
